= Natalia Kusek

*Phone*: (44) 7990 486260 +
*Email*: natalia-cv@kusek.info +
*GitHub*: https://github.com/NataliaKusek +
*LinkedIn*: https://uk.linkedin.com/in/nataliakusek/en +
*Website*: http://natalia.kusek.info +
*Address*: Harpenden, UK

== Junior Python Developer

Master of Science in Geodesy, Surveying and Cartography with 1 year experience in GIS and 2 years in land surveying and CAD. Learning Python and SQL.

=== Availability

now

=== Skills

==== Cad
Ewmapa, MikroMap, Microstation, 

==== Database
PostgreSQL, 

==== Gis
ArcGIS, QGIS, 

==== Land surveying
WinKalk, 

==== Office
Microsoft Excel, Microsoft Word, 

==== Programming
Python, SQL, 

==== Tool
Git, GitHub, 


== Experience

=== Junior Python Developer (2017-11 - ), Kusek Ltd (IT), Harpenden, United Kingdom

Position type: ownership

    * Learning Python and SQL. 



Technologies: Python, Git, GitHub, SQL, PostgreSQL, Markdown, 

=== Director (2016-06 - ), Kusek Ltd (IT), Harpenden, United Kingdom

Position type: ownership

    * Running a small IT company. 



Technologies: xero.com, 

=== GIS Technician (2015-11 - 2016-10), Cyient (Telecommunication), Aylesbury, United Kingdom

Position type: contractor via agency

    * Designing fibre network for BT. 



Technologies: ArcGIS, Microsoft Excel, 

=== GIS Technician Intern (2014-11 - 2014-12), GISON (GIS systems provider), Krakow, Poland

Position type: permanent

    * Creating metadata, digitalizing map data. 



Technologies: QGIS, 

=== Land Surveyor Assistant (2011-11 - 2014-10), GEOMAP (Land surveying), Krakow, Poland

Position type: part-time

    * Real estate divisions, resumptions of border, maps updates. 



Technologies: Microsoft Word, WinKalk, MikroMap, Ewmapa, 

=== Land Surveyor Assistant (2010-06 - 2010-08), GEOPROF (Land surveying), Krakow, Poland

Position type: permanent

    * Maps updates. 



Technologies: Microstation, 


== Recommendations
"Natalia is working fast and efficient and good result oriented, he´s opened to learn new things."
Mariusz Krukar, October 8, 2016


== Learning

=== Education

University of Agriculture in Krakow (2006 - 2011), Agricultural Land Surveying and Property Appraisal


=== Conferences / trainings

Programming for Everybody (Getting Started with Python) (2015)

Python Data Structures (2015)


=== Other

Currently learning ArcGIS and Python.

=== Last updated

1/18/18

